config/routes.rb
Rails.application.routes.draw do

  get 'message/new'

  # resources :albums
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',       to: 'static_pages#help'
  get  '/about',      to: 'static_pages#about'
  get  '/contact',    to: 'messages#new'
  get  '/campground', to: 'static_pages#campground'
  get  '/blog', to: 'static_pages#blog'

  get '/campground-album', to: 'albums#campground'

  get  '/signup',     to: 'users#new'
  post '/signup',     to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :messages, only: [:new, :create]

  resources :users
  resources :albums
  resources :posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :topic
  validates :title, :topic_id, presence: true

  scope :campground_album_items, -> {where(topic_id: '1')}
  mount_uploader :image, ImageUploader

  def self.by_position
    order("position ASC")
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :find_album_item, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :update, :destroy, :edit]

  def index
    @album_items = Album.by_position

    if params[:category].blank?
      @album_items = Album.by_position
    else
      @topic_id = Topic.find_by(name: params[:topic_id]).id
      @album_items = Album.where(topic_id: @topic_id).order("created_at DESC")
    end
  end

  def campground
    @campground_album_items = Album.campground_album_items.by_position
  end

  def new
    @album_item = Album.new
  end

  def create
    @album_item = Album.new(params.require(:album).permit(:title, :topic_id, :image))

    respond_to do |format|
      if @album_item.save
        format.html { redirect_to albums_path, success: 'Your photo item is now live.' }
      else
        format.html { render :new }
      end
    end
  end


  def edit
    @album_item = Album.find(params[:id])
  end

  def update
    @album_item = Album.find(params[:id])
    
    respond_to do |format|
      if @album_item.update(params.require(:album).permit(:title, :topic_id, :image))
        format.html { redirect_to albums_path, success: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @album_item = Album.find(params[:id])
  end

  def destroy
    @album_item = Album.find(params[:id])
    @album_item.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, success: 'Photo was removed.' }
    end
  end


  private

  def post_params
    params.require(:album).permit(:title, :category_id, :image)
  end

  def find_album_item
    @album_item = Album.find(params[:id])
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless logged_in? && current_user.admin?
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_item.html.erb
<div class="card">

  <%= link_to(image_tag(album_item.image_url(:medium).to_s, class: 'img-fluid post-image center-block'), album_item.image_url(:default).to_s, class: 'img-fluid post-image center-block',
              data: {lightbox: "albumphotos", title: album_item.title}) %>

  <p class="card-text">
    <span><%= link_to album_item.title, album_item %> </span>
    </p>


  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit", edit_album_path(album_item.id) %>
    <%= link_to "Delete Photo", album_path(album_item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

</div>

app/views/albums/_form.html.erb
<%= form_for(@album_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Type the post title here', class: 'form-control' %>

    <%= f.label :Category %> <br>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title, {prompt: 'Choose an album' }) %><br>

    <div class="field">
        <%= f.file_field :image, class: 'btn btn-default'  %>
    </div>
  </div>

  <hr>

  <div class="actions">
    <%= f.submit 'Submit photo', class: "btn btn-default btn-lg" %>
  </div>
<% end %>

app/views/albums/campground.html.erb
<div class="album text-muted">

  <div class="container">

    <div class="row wow fadeIn " data-wow-delay="0.2s">
      <div class="col-md-12 mt-5">
        <h2 class="h1-responsive font-bold">
          Campground Photo Gallery
        </h2>
        <hr>

      </div>
    </div>



    <div class="row sortable">
      <% @campground_album_items.each do |item| %>
        <div class="card"> 
          <%= image_tag item.image_url(:medium).to_s   %>
          <p class="card-text">  <%= link_to item.title, album_path(item) %> </p>
          <%= link_to 'Edit', edit_album_path(item.id) %>
          <%= link_to 'Delete Photo', album_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <%end%>

    </div>

    <hr>

  </div>

</div>

app/views/albums/edit.html.erb
<% provide(:title, 'Edit Photo') %>


<div class="container">

  <div class="row wow fadeIn" data-wow-delay="0.2s">
    <div class="col-md-12 mt-5">
      <h2 class="h1-responsive font-bold">
        Edit Photo
      </h2>
    </div>
  </div>

<%= render 'form', album_item: @album_item %>


</div>

app/views/albums/estate_park.html.erb
<div class="album text-muted">

  <div class="container">

    <div class="row wow fadeIn " data-wow-delay="0.2s">
      <div class="col-md-12 mt-5">
        <h2 class="h1-responsive font-bold">
          The Village Photo Gallery
        </h2>
        <hr>
        <p>
          <%= link_to "Campground", campground_album_path, :class => 'btn btn-default' %> 
          <%= link_to "River Run", river_run_album_path, :class => 'btn btn-default' %>
          <%= link_to "The Village", estate_park_album_path, :class => 'btn btn-default' %>
        </p>
      </div>
    </div>

    <hr>

    <div class="row sortable">
      <% @estate_park_album_items.each do |item| %>
        <div class="card"> 
          <%= image_tag item.image_url(:medium).to_s  %>
          <p class="card-text">  <%= link_to item.title, album_path(item) %> </p>
          <%= link_to "Edit", edit_album_path(item.id) %>
          <%= link_to 'Delete Photo', album_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <%end%>

    </div>

    <hr>

  </div>

</div>

app/views/albums/index.html.erb
<% provide(:title, 'Photo Gallery') %>

<div class="album text-muted">

  <div class="container">

    <div class="row wow fadeIn " data-wow-delay="0.2s">
      <div class="col-md-12 mt-5">
        <h2 class="h1-responsive font-bold">
           Photo Gallery
        </h2>

        <hr>

        <ul class="list-inline intro-social-buttons">

          <% if logged_in? && current_user.admin?  %>
            <li class="inline-btn">
              <%= link_to "Add New Photo", new_album_url, :class => 'btn btn-default' %>
            </li>
          <% end %>
        </ul>



        <div class="row sortable sortable">
          <%= render partial: 'album_item', collection: @album_items %>
        </div>

        <hr>

      </div>

    </div>
  </div>
</div>

app/views/albums/new.html.erb
<% provide(:title, 'Add new photo') %>



<div class="container">

  <h2 class="h1-responsive font-bold login-top">Add New Photo</h2>

  <div class="row wow Fadein" data-wow-delay="0.2s">
    <div class="col-md-12 col-md-offset-3">
      <%= render 'form', album_item: @album_item %>
    </div>
  </div>
</div>

app/views/albums/river_run.html.erb
<div class="album text-muted">

  <div class="container">

    <div class="row wow fadeIn " data-wow-delay="0.2s">
      <div class="col-md-12 mt-5">
        <h2 class="h1-responsive font-bold">
          River Run Photo Gallery
        </h2>
        <hr>
        <p>
          <%= link_to "Campground", campground_album_path, :class => 'btn btn-default' %> 
          <%= link_to "River Run", river_run_album_path, :class => 'btn btn-default' %>
          <%= link_to "The Village", estate_park_album_path, :class => 'btn btn-default' %>
        </p>
      </div>
    </div>

    <hr>

    <div class="row sortable">
      <% @river_run_album_items.each do |item| %>
        <div class="card"> 
          <%= image_tag item.image_url(:medium).to_s %>
          <p class="card-text">  <%= link_to item.title, album_path(item) %> </p>
          <%= link_to "Edit", edit_album_path(item.id) %>
          <%= link_to 'Delete Photo', album_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <%end%>

    </div>

    <hr>

  </div>

</div>

app/views/albums/show.html.erb
<div class="post-container container">

  <div class="row">


    <!--Card-->
    <div class="card card-cascade wider reverse my-4 card-post-show">

      <!--Card image-->
      <div class="view overlay">

        <%= link_to(image_tag(@album_item.image_url(:default).to_s, class: 'img-fluid post-image center-block'), @album_item.image_url(:default).to_s, class: 'img-fluid post-image center-block',
                    data: {lightbox: @album_item.id, title: @album_item.title}) %>
      </div>
      <!--/Card image-->

      <!--Card content-->
      <div class="card-body text-center">

        <!--Title-->
        <h4 class="card-title"><strong><%= link_to @album_item.title, @album_item %></strong></h4>
        <h5 class="indigo-text"><strong><%= @album_item.created_at.strftime("%d %b. %Y") %></strong></h5>



        <% if logged_in? && current_user.admin? %>
          <%= link_to "Edit", edit_album_path(@album_item.id) %>
          <%= link_to "Delete Photo", album_path(@album_item), method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>



    </div>

  </div>
</div>