config/routes.rb
Rails.application.routes.draw do

  get 'message/new'

  # resources :albums
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',       to: 'static_pages#help'
  get  '/about',      to: 'static_pages#about'
  get  '/contact',    to: 'messages#new'
  get  '/campground', to: 'static_pages#campground'
  get  '/blog', to: 'static_pages#blog'

  get '/campground-album', to: 'albums#campground'

  get  '/signup',     to: 'users#new'
  post '/signup',     to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :messages, only: [:new, :create]

  resources :users
  resources :albums
  resources :posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer center-on-small-only ">

  <div class="container">

    <div class="row my-4">

      <div class="col-lg-3 col-md-6">
        <p>
          <%= link_to "Home",   root_path %>
        </p>
      </div>

      <hr class="w-100 clearfix d-sm-none">

      <div class="col-lg-2 col-md-6 ml-auto ">
        <p>
          <%= link_to "About",   about_path %>
        </p>
      </div>

      <hr class="w-100 clearfix d-sm-none">

      <div class="col-lg-2 col-md-6 ml-auto ">
        <p>
          <%= link_to "Contact",   contact_path %>
        </p>
      </div>

      <hr class="w-100 clearfix d-sm-none">

      <div class="col-lg-2 col-md-6 ml-auto ">
        <p>
          <%= link_to "Help",   help_path %>
        </p>
      </div>

    </div>

  </div>



  <!--Copyright-->
  <div class="footer-copyright">
    <div class="containter-fluid">
      © 2019 Copyright:
      Roberts Enterprise
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" >

  <div class="container">

    <!-- Navbar brand -->
    <%= link_to "Roberts Corey Lake Campground", root_path, {:class => "navbar-brand" } %>

      <!-- Collapse button -->
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent-7"  aria-controls="navbarSupportedContent-7"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
      <ul class="navbar-nav mr-auto">

        <!-- Links -->
        <li class="nav-item">
          <%= link_to "Home", root_path, {:class => "nav-link waves-effect waves-light"}  %>
        </li>
        <li class="nav-item">
        <%= link_to "Blog", posts_path, {:class => "nav-link waves-effect waves-light"}  %>
        </li>

        <li class="nav-item">
          <%= link_to "About", about_path, {:class => "nav-link waves-effect waves-light"}  %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, {:class => "nav-link waves-effect waves-light"}  %>
        </li>
        <li class="nav-item">
          <%= link_to "Photos", albums_path, {:class => "nav-link waves-effect waves-light"}  %>
        </li>

        <!-- Dropdown -->
        <% if logged_in? %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account <b class="caret"> </b>
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">



                <%= link_to "Profile", current_user, {:class => "dropdown-item"}  %>

                <%= link_to "Settings", edit_user_path(current_user), {:class => "dropdown-item"}  %>




                <%= link_to "Log out", logout_path, {method: :delete , :class => "dropdown-item" } %>

            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, {:class => "nav-link waves-effect waves-light"} %>
          </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<%= stylesheet_link_tag    'side-nav' %>



  <div id="wrapper">

    <div class="overlay"></div>

    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
      <ul class="nav sidebar-nav">
        <li class="sidebar-brand"> <a href="#">Dashboard </a> </li>

        <li>
        <%= link_to root_path do  %>
          <i class="fa fa-fw fa-home"></i>
          <span class="network-name">Home</span>
        <% end %>
        </li>

        <li>
          <%= link_to campground_path do  %>
            <i class="fa fa-tree fa-fw"></i>
            <span class="network-name">Campground</span>
          <% end %>
        </li>

        <li>
          <%= link_to albums_path do  %>
            <i class="fa fa-camera-retro fa-fw"></i>
            <span class="network-name">Gallery</span>
          <% end %>
        </li>
        <li>
          <%= link_to posts_path do  %>
            <i class="fa fa-rss fa-fw"></i>
            <span class="network-name">Blog</span>
          <% end %>
        </li>

        <li>
          <%= link_to contact_path do  %>
            <i class="fa fa-envelope fa-fw"></i>
            <span class="network-name">Contact</span>
          <% end %>
        </li>

        <li>
          <%= link_to help_path do  %>
            <i class="fa fa-question-circle fa-fw"></i>
            <span class="network-name">Help</span>
          <% end %>
        </li>



      </ul>
    </nav>
    <!-- /#sidebar-wrapper -->

    <%= yield(:content) %>





  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="full-height">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag asset_path('favicon/favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <%= stylesheet_link_tag    'application' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin=""/>

    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
            integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
            crossorigin=""></script>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>


      <%= render :partial => 'shared/flash_messages', :flash => flash %>

    <%- # 'yield' below will insert content from the view -%>

      <%= yield%>

      <%= render 'layouts/footer' %>




    <%= javascript_include_tag 'application' %>


      <script type="text/javascript">
          new WOW().init();
      </script>




  </body>
</html>

app/views/layouts/dashboardlayout.html.erb
<!DOCTYPE html>
<html lang="en" class="full-height">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag asset_path('favicon/favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <%= stylesheet_link_tag 'application'  %>



  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>



  <%= render 'layouts/sidebar' %>

  <%= render :partial => 'shared/flash_messages', :flash => flash %>


  <%= render 'layouts/footer' %>

  <%= javascript_include_tag 'application' %>


  <script type="text/javascript">
    new WOW().init();
  </script>




</body>
</html>